#!/usr/bin/env bash
#last=""
#
#socat - UNIX-CONNECT:"$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" |
#  while read -r line; do
#    [[ "$line" == workspace* ]] || continue
#
#    # Ask Hyprland what is ACTUALLY active right now
#    ws="$(hyprctl activeworkspace -j | jq -r '.id')"
#
#    [[ "$ws" == "$last" ]] && continue
#    last="$ws"
#    : >/tmp/current_workspace
#    echo "$ws" >>/tmp/current_workspace
#  done

last=""

# Output the current workspace immediately on start
hyprctl activeworkspace -j | jq -r '.id'

# Listen for Hyprland events
socat -u UNIX-CONNECT:"$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - |
  stdbuf -o0 grep --line-buffered "^workspace>>" |
  while read -r line; do
    # Ask Hyprland what is ACTUALLY active right now
    ws="$(hyprctl activeworkspace -j | jq -r '.id')"

    if [[ "$ws" != "$last" ]]; then
      echo "$ws" # Eww reads this line directly
      last="$ws"
    fi
  done
