include ~/.cache/wal/colors-kitty.conf

background_opacity 0.5
background_tint 1
# Padding around the text area (in pixels)
window_padding_width 10
font_family GeistMono Nerd Font
font_size 14
cursor_trail 10
confirm_os_window_close 0
