#########################
### Modular Hypr Config ###
#########################
source = ~/.config/hypr/
source = ~/.config/hypr/hyprland_conf/
source = ~/.config/hypr/hyprland_conf/monitors.conf
source = ~/.config/hypr/hyprland_conf/programs.conf
source = ~/.config/hypr/hyprland_conf/autostart.conf
source = ~/.config/hypr/hyprland_conf/env.conf
source = ~/.config/hypr/hyprland_conf/lookfeel.conf
source = ~/.config/hypr/hyprland_conf/input.conf
source = ~/.config/hypr/hyprland_conf/keybinds.conf
