-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--################

--## AUTOSTART ###

--################

-- Launch scripts & status bars once





















-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon &")
    hl.exec_cmd("eww daemon &")
    hl.exec_cmd("hyprpm enable hyprexpo")
    hl.exec_cmd("hyprpm enable hyprscrolling")
    hl.exec_cmd("hyprpm reload")
    hl.exec_cmd("/home/arkaive19/.config/hypr/scripts/toggle_bar.sh")
    hl.exec_cmd("sleep 2 && nm-applet &")
    hl.exec_cmd("sleep 2 && blueman-applet &")
    hl.exec_cmd("hypridle &")
    hl.exec_cmd("fcitx5 &")
    hl.exec_cmd("swayosd-server &")
    hl.exec_cmd("/home/arkaive19/.config/eww/bar/workspace &")
    hl.exec_cmd("hyprexpose &")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/xdg-desktop-portal-hyprland &")
    hl.exec_cmd("/usr/lib/xdg-desktop-portal &")
    hl.exec_cmd("/usr/lib/xdg-desktop-portal-gtk &")
end)
