-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'
local wal = dofile(os.getenv("HOME") .. "/.cache/wal/colors-hyprland.lua")
local active_color = wal.color11

return {
	active_border = active_color,
}
