-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--############################

--## ENVIRONMENT VARIABLES ###

--############################

hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")

hl.env("HYPRCURSOR_SIZE", 24)
