-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--################

--## INPUT ###

--################

hl.config({
    input = {
        kb_layout = "us",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = false,
            disable_while_typing = false,
        },
    },
})

-- TODO: manual review: gesture = 3, "horizontal", "workspace"

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})
