-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--###############

--## MONITORS ###

--###############

hl.monitor({
    output   = "eDP-2",
    mode     = "1920x1200@165",
    position = "0x0",
    scale    = 1,
})
