-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--##################

--## MY PROGRAMS ###

--##################

-- Set default apps

terminal = "kitty"
fileManager = "thunar"
menu = "rofi -show drun"
submenu = "wofi --show drun"
