#################
### AUTOSTART ###
#################

# Launch scripts & status bars once

exec-once = awww-daemon &
exec-once = eww daemon &
exec-once = eww open bar && eww open fakecorner
exec-once = sleep 2 && nm-applet &
exec-once = sleep 2 && blueman-applet &
exec-once = hypridle &
exec-once = swayosd-server &
exec-once = /home/arkaive19/.config/eww/bar/workspace &

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = /usr/lib/xdg-desktop-portal-hyprland &
exec-once = /usr/lib/xdg-desktop-portal &
exec-once = /usr/lib/xdg-desktop-portal-gtk &
